app/models.py
from .extensions import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    uid = db.Column(db.Integer, primary_key=True,autoincrement=True)
    username = db.Column(db.String(50) , nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    
    def set_password(self,password):
        self.password = generate_password_hash(password)
    
    def check_password(self,password):
        return check_password_hash(self.password,password)
        
    def get_id(self):
        return self.uid
    
    def __repr__(self):
        return f"<UID: {self.uid} User: {self.username}>"

class LikedSong(db.Model):
    sid = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(400), nullable=False)
    author = db.Column(db.String(200))

app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_login = SubmitField('Login')
    
    class Meta:
        csrf = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.csrf_token.id = 'csrf_token_login'
    
class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit_register = SubmitField('Register')
    
    class Meta:
        csrf = True

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.csrf_token.id = 'csrf_token_register'

app/__init__.py
from flask_login import login_required
from app.models import User
from app.blueprints import auth_bp, main_bp
from flask import Flask, jsonify, redirect, render_template, url_for
from .extensions import db, login_manager, migrate, csrf
from flask_wtf.csrf import generate_csrf


def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')
    
    db.init_app(app)
    migrate.init_app(app,db)
    login_manager.init_app(app)
    csrf.init_app(app)
    login_manager.login_view = 'auth.auth'
    
    with app.app_context():
        from flask_migrate import upgrade
        upgrade()
    
    app.register_blueprint(auth_bp, url_prefix='/auth')
    app.register_blueprint(main_bp, url_prefix='/main')
    
    @app.route('/api/csrf-token', methods=['GET'])
    def csrf_token():
        token = generate_csrf()
        return jsonify({'csrf_token': token})
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    @app.route('/')
    @login_required
    def index():
        return redirect(url_for('main.index'))
    
    @app.route("/site-map")
    def site_map():
        links = []
        for rule in app.url_map.iter_rules():
            # Filter out rules we can't navigate to in a browser
            # and rules that require parameters
            if "GET" in rule.methods and has_no_empty_params(rule):
                url = url_for(rule.endpoint, **(rule.defaults or {}))
                links.append((url, rule.endpoint))
        return '<br>'.join(['<a href="{url}">{endpoint}</a>'.format(url=url, endpoint=endpoint) for url, endpoint in links])
    
    
    return app

def has_no_empty_params(rule):
    defaults = rule.defaults if rule.defaults is not None else ()
    arguments = rule.arguments if rule.arguments is not None else ()
    return len(defaults) >= len(arguments)

app/blueprints/__init__.py
from .auth import auth_bp
from .main import main_bp

app/blueprints/main/__init__.py
from flask import Blueprint
main_bp = Blueprint('main', __name__)

from .routes import *

app/blueprints/main/routes.py
from . import main_bp
from flask import render_template, redirect, url_for
from flask_login import login_required


@main_bp.route('/')
@login_required
def index():
    return render_template('main/index.html')

@main_bp.route('/search')
@login_required
def search():
    return render_template('main/search.html')

app/templates/base.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}MyMusic{% endblock %}</title>
        <!-- Bootstrap 5 CSS -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"> -->
        {% block head %}{% endblock %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    </head>
    <body>
        <!-- Navbar -->
         <header>
            <nav aria-label="Main navigation">
                <a id="navbar-brand" href="#">My Music</a>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="nav-items">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.search') }}">Search</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/playlists">Playlists</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        </li>
                    </ul>
                </div>
                
            </nav>

            
        </header>
        
        <!-- Main Content -->
        <main class="page-container">
            {% block content %}{% endblock %}
        </main>

        <!-- Footer -->
        <!-- <footer>
            <p>&copy; 2025 MyMusic. All rights reserved.</p>
        </footer> -->

        <!-- Bootstrap 5 JS Bundle -->
        <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script> -->
        {% block scripts %}{% endblock %}
    </body>
    </html>

app/templates/main/index.html
{% extends 'base.html' %}

<!-- CSS Links -->
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/index.css') }}">
{% endblock %}

<!-- Main page content -->
{% block content %}
    <h2>Welcome {{ current_user.username }}</h2>
    <section class="history">
        <h2>History</h2>
        <div class="history-container">
            <!-- <buttton class="clear-history-btn">Clear History</buttton> -->
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
            
            <div class="history-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Song cover" class="history-img">
                <div class="history-info">
                    <p class="song-title">Name</p>
                    <p class="song-artist">Artist</p>
                </div>
            </div>
    </section>

    <section class="playlist">
        <h2>Playlists</h2>
        <div class="playlist-container">
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>
            
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>
            
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>
            
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>
            
            
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>
            
            <div class="playlist-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="Playlist cover" class="playlist-img">
                <div class="playlist-info">
                    <p class="playlist-name">Playlist Name</p>
                </div>
            </div>

        </div>
        
    </section>
{% endblock %}

<!-- Js Links -->
{% block scripts %}
<script>
    // js to handle horizontal scroll on history 
    const history = document.querySelector('.history-container');
    history.addEventListener('wheel', (e) => {
        e.preventDefault();
        history.scrollLeft += e.deltaY;
    })
</script>

{% endblock %}

app/templates/main/search.html
{% extends 'base.html' %}

<!-- CSS Links -->
{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/search.css') }}">
{% endblock %}

<!-- Main page content -->
{% block content %}
    <div class="search-container">
        <!------- Search bar ------->
        <div class="search-bar">
            <i class="fa fa-search search-icon"></i>
            <input type="text" id="search-input" placeholder="Search...">
        </div>

        <!------- Search Results ------->
        <div class="search-results">
            <!-- Result item -->
            <div class="result-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="search result image" />
                <div class="result-info">
                    <h3 class="song-title">Song name</h3>
                    <p class="artist">Artist</p>
                    <p class="extra-info">
                        <span class="duration">3:00</span>
                        <span class="album">Album</span>
                        <span class="likes">80k</span>
                    </p>
                </div>
                <div class="controls">
                    <button class="play-btn"><i class="fa fa-play play-icon"></i></button>
                    <!-- <button class="play-btn"><i class="fa fa-pause play-icon"></i></button> -->
                </div>
            </div>
            <!--  -->
            <div class="result-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="search result image" />
                <div class="result-info">
                    <h3 class="song-title">Song name</h3>
                    <p class="artist">Artist</p>
                    <p class="extra-info">
                        <span class="duration">3:00</span>
                        <span class="album">Album</span>
                        <span class="likes">80k</span>
                    </p>
                </div>
                <div class="controls">
                    <button class="play-btn"><i class="fa fa-play play-icon"></i></button>
                    <!-- <button class="play-btn"><i class="fa fa-pause play-icon"></i></button> -->
                </div>
            </div>

            <div class="result-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="search result image" />
                <div class="result-info">
                    <h3 class="song-title">Song name</h3>
                    <p class="artist">Artist</p>
                    <p class="extra-info">
                        <span class="duration">3:00</span>
                        <span class="album">Album</span>
                        <span class="likes">80k</span>
                    </p>
                </div>
                <div class="controls">
                    <button class="play-btn"><i class="fa fa-play play-icon"></i></button>
                    <!-- <button class="play-btn"><i class="fa fa-pause play-icon"></i></button> -->
                </div>
            </div>

            <div class="result-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="search result image" />
                <div class="result-info">
                    <h3 class="song-title">Song name</h3>
                    <p class="artist">Artist</p>
                    <p class="extra-info">
                        <span class="duration">3:00</span>
                        <span class="album">Album</span>
                        <span class="likes">80k</span>
                    </p>
                </div>
                <div class="controls">
                    <button class="play-btn"><i class="fa fa-play play-icon"></i></button>
                    <!-- <button class="play-btn"><i class="fa fa-pause play-icon"></i></button> -->
                </div>
            </div>

            <div class="result-item">
                <img src="{{ url_for('static', filename='images/image.png') }}" alt="search result image" />
                <div class="result-info">
                    <h3 class="song-title">Song name</h3>
                    <p class="artist">Artist</p>

                    <p class="extra-info">
                        <span class="album">Album</span>
                        <span class="duration">3:00</span>
                        <span class="likes">80k</span>
                    </p>
                </div>
                <div class="controls">
                    <button class="play-btn"><i class="fa fa-play play-icon"></i></button>
                    <!-- <button class="play-btn"><i class="fa fa-pause play-icon"></i></button> -->
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- Js Links -->
{% block scripts %}
{% endblock %}